Dummy Experiment
Lichtwerkstatt/XRTL_SPA pull request #20
Opened 2021-12-10 09:16 UTC by Claralein

Server neue socket.on Befehle hinzufegügt & neuen Test-Odner anglegt mit .js für Befehlsüberprüfung

2021-12-10 10:03 UTC, jkbeetle requested changes
:) testing the review functionality of Github

2021-12-10 10:03 UTC, jkbeetle commented on test/dummy_exp.js
> +socket.on("rotationControl", () => {
please use events as defines in the wiki: https://github.com/Lichtwerkstatt/XRTL_SPA/wiki/Communication-Protocol
for example for rotation 
event "command"
payload: {userId, componentId, controlId, command {steps}}

2021-12-10 10:03 UTC, jkbeetle commented on test/dummy_exp.js
> +    socket.emit('rotationControl', { username: "user1234", componentId: "km100_1", controlId: "top", steps: 100 });
on rotation:
-  emit status update with busy true
- wait a certain amount of time to simulate duration of rotation
- emit status update with busy false and updated rotation

2021-12-10 10:03 UTC, jkbeetle commented on test/dummy_exp.js
> +
we need global rotation status of dummy components in the dummy experiment.
For now: two KM100 (ids: KM100_1 and KM100_2) with each to stepper motors ("top" and "bootom")

2021-12-13 08:49 UTC, Claralein commented
Änerungen vorgenommen.
Bitte Überprüfen, ob sie den Forderungen gerecht werden :)

2021-12-13 21:30 UTC, merged